# action.yml
name: 'Docker Run Action'
description: 'Run a command in a new container'
inputs:
  scan_dir:
    description: 'scan_dir'
    required: true
  working_dir:
    description: 'working_dir'
    required: true
  git_url:
    description: 'git_url'
    required: true
  api_key:
    description: 'api_key'
    required: true
  username:
    description: 'Username'
    required: false
  password:
    description: 'Password'
    required: false
  docker_network:
    description: 'Docker Network ID'
    default: ${{ job.container.network }}
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'